apiVersion: storage.dell.com/v1
kind: CSIPowerStore
metadata:
  name: test-powerstore
  namespace: test-powerstore
spec:
  driver:
    # Config version for CSI PowerStore v2.2 driver
    configVersion: v2.2.0
    # Controller count
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    common:
      # Image for CSI PowerStore driver v2.2
      image: "dellemc/csi-powerstore:v2.2.0"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi"
        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
          value: "/etc/fc-ports-filter"
    sideCars:
      # Uncomment the following to install 'external-health-monitor' sidecar to enable health monitor of CSI volumes from Controller plugin.
      # Also set the env variable controller.envs.X_CSI_HEALTH_MONITOR_ENABLED to "true".
      #- name: external-health-monitor
      #  args: ["--monitor-interval=60s"]

    controller:
      envs:
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from Controller plugin- volume status, volume condition.
        # Install the 'external-health-monitor' sidecar accordingly.
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"
      
        # X_CSI_NFS_ACLS: enables setting permissions on NFS mount directory
        # This value will be the default value if a storage class and array config in secret 
        # do not contain the NFS ACL (nfsAcls) parameter specified
        # Permissions can be specified in two formats:
        #   1) Unix mode (NFSv3)
        #   2) NFSv4 ACLs (NFSv4)
        #      NFSv4 ACLs are supported on NFSv4 share only.
        # Allowed values:
        #   1) Unix mode: valid octal mode number
        #      Examples: "0777", "777", "0755"
        #   2) NFSv4 acls: valid NFSv4 acls, seperated by comma
        #      Examples: "A::OWNER@:RWX,A::GROUP@:RWX", "A::OWNER@:rxtncy"
        # Optional: true
        # Default value: "0777"
        # nfsAcls: "0777"
        - name: X_CSI_NFS_ACLS
          value: "0777"
          
      # nodeSelector: Define node selection constraints for controller pods.
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      # Examples:
      #   node-role.kubernetes.io/master: ""
      nodeSelector:
      #   node-role.kubernetes.io/master: ""

      # tolerations: Define tolerations for the controllers, if required.
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      #  - key: "node-role.kubernetes.io/master"
      #    operator: "Exists"
      #    effect: "NoSchedule"    

    node:
      envs:
        # Set to "true" to enable ISCSI CHAP Authentication
        # CHAP password will be autogenerated by driver
        - name: "X_CSI_POWERSTORE_ENABLE_CHAP"
          value: "true"
        # X_CSI_HEALTH_MONITOR_ENABLED: Enable/Disable health monitor of CSI volumes from node plugin- volume usage, volume condition
        # Allowed values:
        #   true: enable checking of health condition of CSI volumes
        #   false: disable checking of health condition of CSI volumes
        # Default value: false
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "false"

      # nodeSelector: Define node selection constraints for node pods.
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      # Examples:
      #   node-role.kubernetes.io/worker: ""
      nodeSelector:
      #   node-role.kubernetes.io/worker: ""

      # tolerations: Define tolerations for the controllers, if required.
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      #  - key: "node-role.kubernetes.io/worker"
      #    operator: "Exists"
      #    effect: "NoSchedule"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerstore-config-params
  namespace: test-powerstore
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: "debug"
    CSI_LOG_FORMAT: "JSON"
