name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the formatter, linter, and vetter
        uses: dell/common-github-actions/go-code-formatter-linter-vetter@main
        with:
          directories: ./...
  go_security_scan:
    name: Go security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Go Security
        uses: securego/gosec@master
        with:
          args: -exclude=G108,G402,G307,G101,G404 ./...
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17+
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Checkout dell-csi-operator
        uses: actions/checkout@v2
        with:
          repository: 'dell/dell-csi-operator'
          path: 'dell-csi-operator'
      - name: Run unit tests and check package coverage
        run: make unit-test
  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
  image_security_scan:
    name: Image Scanner
    runs-on: ubuntu-latest
    env:
      BASE_IMG : ubuntu:latest
    steps:
      - name: Set up Go 1.17+
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build Docker Images
        run: docker build . -t dell-csi-operator:latest
      - name: Scan operator Image
        uses: Azure/container-scan@v0
        with:
          image-name: dell-csi-operator:latest
          severity-threshold: HIGH
